name: npm test 1
on: 
  workflow_dispatch:
               
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          
      - name: install
        run: npm install

test:
  run-on: ubuntu-latest
  needs: install
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'

- name: test
run: npm install


